site_name: "Teaching for Impact: Designing Effective & Open Training"
site_url: https://talarifyza.github.io/teaching-for-impact/

use_directory_urls: true

theme:
  name: material
  logo: 
  favicon: 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - toc.integrate
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow          # Highlight on scroll

  palette:
    - scheme: default


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/passwords.js

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - tables
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true      # Add anchor links
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 2       # Maximum depth

plugins:
  - glightbox
  - search
  - macros:
      include_dir: includes


extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject

copyright: >
  Copyright &copy; 2026 Failure Modes of Engineering - <a href="#__consent">Change cookie settings</a>
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Part 1 - Designing Training:
      - Overview: part-1/index.md
      - 1. Getting Started: part-1/lesson-1.md
      - 2. Understanding Your Learners: part-1/lesson-2.md
      - 3. How People Learn: part-1/lesson-3.md
      - 4. Learning Outcomes: part-1/lesson-4.md
      - 5. Co-Design and Constraints: part-1/lesson-5.md
      - 6. Designing Learning Experiences: part-1/lesson-6.md
      - 7. Practice, Feedback, and Iteration: part-1/lesson-7.md
      - 8. Assessment and Evaluation: part-1/lesson-8.md
  - Part 2 - From Training Design to OER:
      - Overview: part-2/index.md
      - 1. Designing for Openness: part-2/lesson-1.md
      - 2. Finding and Evaluating Existing OER: part-2/lesson-2.md
      - 3. What Makes Resources Open?: part-2/lesson-3.md
      - 4. Adapting, Remixing, and Localising OER: part-2/lesson-4.md
      - 5. Sharing and Publishing OER: part-2/lesson-5.md
      - 6. Sustaining and Improving OER: part-2/lesson-6.md      
  - Conclusion: conclusion.md
  - Activity Templates:
      - Overview: activities/index.md
      - 1. System Map: activities/template_1_system_map.md 
      - 2. Theory of Change: activities/template_2_theory_of_change.md
      - 3. Learner Reality Mapping: activities/template_3_learner_reality.md
      - 4. Learning Experience Audit: activities/template_4_learner_exp_audit.md
      - 5.  Learning Outcomes: activities/template_5_learning_outcomes.md
      - 6. Alignment Table: activities/template_6_alignment.md  
      - 7. Co-Design Plan: activities/template_7_co_design.md  
      - 8. Learning Activity Design: activities/template_8_activity_design.md  
      - 9. Practice & Feedback Plan: activities/template_9_practice_feedback.md  
      - 10. Assessment & Evaluation Plan: activities/template_10_assess_evaluate.md  
      - 11.Training Design Snapshot: activities/template_11_snapshot.md  
      - 12. OER Workflow: activities/template_12_oer.md
  - Resources:
      - Glossary: resources/glossary.md
      - Bloom's Taxonomy Cheatsheet: resources/blooms-taxonomy.md
      - Offline Access: resources/offline-access.md